name: MJH Projects
favicon: null
layout_spectrum: 0.27955920388922095
typography_spectrum: 0.5205670518334955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6581144444644451
  lightness: 0.8948556841351092
  saturation: 0.3569222001824528
  rhythmicContrast: 0.4837769779842347
purpose: []
